language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3

install:
  - sudo apt-get install -qq libeigen3-dev
  - pip install cython==0.19.2 --use-mirrors
  - cython --version

script:
  - BENCHMARK=1 python setup.py -v test
